version: '3.7'
volumes:
  mongo-be-cache:
  mongo-be-config:
  mongo-fe-cache:
  pgdata:
  npm-cache:

services:
  bootstrap-npm-install:
    env_file:
      - .env
    build:
      dockerfile: DockerfileNpmCache
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
        - http_proxy=${DOCKER_HTTP_PROXY}
        - https_proxy=${DOCKER_HTTPS_PROXY}
        - no_proxy=
    volumes:
      - npm-cache:/opt/npmcache
      - ./var/npm/rafbs-node_modules:/usr/src/rafbs/node_modules
      - ./var/npm/rafbcs-node_modules:/usr/src/rafbcs/node_modules
      - ./var/npm/rafbfe-node_modules:/usr/src/rafbfe/node_modules

  temp-store:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

  back-end-cache-db:
    build:
      context: ./back-end-cache-db
    volumes:
      - mongo-be-cache:/data
      - ./back-end-cache-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: always
    ports: 
      - "27019:27017"

  back-end-config-db:
    build:
      context: ./config-db
    volumes:
      - mongo-be-config:/data
      - ./config-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: always
    ports: 
      - "27017:27017"

  front-end-cache-db:
    build:
      context: ./front-end-cache-db
    volumes:
      - mongo-fe-cache:/data
      - ./front-end-cache-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    restart: always
    ports: 
      - "27018:27017"

  registrationservice:
    build: 
      context: ./register-a-food-business-service
      args:
        - NPM_TOKEN=${NPM_TOKEN}
        - http_proxy=${DOCKER_HTTP_PROXY}
        - https_proxy=${DOCKER_HTTPS_PROXY}
        - no_proxy=
    env_file: 
      - .env-registration-service
    ports:
      - "4000:4000"
      - "9229:9229"
      - "35729:35729"
    command: "npm run start:docker"
#    command: "tail -f /dev/null"
    volumes:
      - npm-cache:/opt/npmcache
      - ./register-a-food-business-service/src:/usr/src/app/src
      - ./register-a-food-business-service/reports:/usr/src/app/reports
      - ./register-a-food-business-service/tests:/usr/src/app/tests
      - ./register-a-food-business-service/scripts:/usr/src/app/scripts
      - ./register-a-food-business-service/docs:/usr/src/app/docs
      - type: bind
        read_only: true
        source: ./var/npm/rafbs-node_modules
        target: /usr/src/app/node_modules

    depends_on:
      - temp-store
      - back-end-cache-db
      - back-end-config-db
      - bootstrap-npm-install

  collections-service:
    build:
      context: ./register-a-food-business-collections-service
      args:
        - NPM_TOKEN=${NPM_TOKEN}
        - http_proxy=${DOCKER_HTTP_PROXY}
        - https_proxy=${DOCKER_HTTPS_PROXY}
        - no_proxy=
    env_file:
      - .env-collections-service
    ports:
      - "4001:4001"
    depends_on:
      - temp-store
      - bootstrap-npm-install
    command: "npm run start"
    volumes:
      - npm-cache:/opt/npmcache
      - ./register-a-food-business-collections-service/src:/usr/src/app/src
      - ./register-a-food-business-collections-service/tests:/usr/src/app/tests
      - ./register-a-food-business-collections-service/scripts:/usr/src/app/scripts
      - ./register-a-food-business-collections-service/docs:/usr/src/app/docs
      - type: bind
        read_only: true
        source: ./var/npm/rafbcs-node_modules
        target: /usr/src/app/node_modules

  front-end:
    build:
      context: ./register-a-food-business-front-end
      args:
        - http_proxy=${DOCKER_HTTP_PROXY}
        - https_proxy=${DOCKER_HTTPS_PROXY}
        - no_proxy=
        - NPM_TOKEN=${NPM_TOKEN}
    env_file:
      - .env-front-end
    ports:
      - "3000:3000"
    depends_on:
      - front-end-cache-db
      - bootstrap-npm-install

    entrypoint: "npm run dev"
    volumes:
      - npm-cache:/opt/npmcache
      - ./register-a-food-business-front-end/src:/usr/src/app/src
      - ./register-a-food-business-front-end/pages:/usr/src/app/pages
      - ./register-a-food-business-front-end/pages_unit_tests:/usr/src/app/pages_unit_tests
      - ./register-a-food-business-front-end/tests:/usr/src/app/tests
      - ./register-a-food-business-front-end/docs:/usr/src/app/docs
      - type: bind
        read_only: true
        source: ./var/npm/rafbfe-node_modules
        target: /usr/src/app/node_modules
