# To execute this docker-compose yml file use `docker compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3.7"
networks:
  rafb:
    external: true

services:
  #  ff-standalone:
  #    image: selenium/standalone-firefox:latest
  #    volumes:
  #      - /dev/shm:/dev/shm
  #
  #    networks:
  #      - rafb
  #
  #
  #  chrome-standalone:
  #    image: selenium/standalone-chrome:latest
  #    volumes:
  #      - /dev/shm:/dev/shm
  #
  #    networks:
  #      - rafb
  #
  #    environment:
  #      - SE_OPTS="-whitelisted-ips="
  #

  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"

    networks:
      - rafb

  chrome:
    image: selenium/node-chrome:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

    networks:
      - rafb

  firefox:
    image: selenium/node-firefox:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

    networks:
      - rafb
